# Generated by Django 3.0.6 on 2020-05-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtext', '0003_remove_user_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default='receiver', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient', to='webtext.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='sender', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to='webtext.User'),
        ),
    ]
