# Generated by Django 3.0.6 on 2020-05-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtext', '0004_auto_20200508_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
